//! Metadata and occupancy masks shared by native generation and runtime lookups.

#[path = "multipliers.rs"]
mod multipliers;

use crate::{Bitboard, Square};
use multipliers::{BISHOP_MULTIPLIERS, ROOK_MULTIPLIERS};

pub(super) const TABLE_LEN: usize = 107_648;

#[derive(Clone, Copy)]
pub(super) struct Magic {
    pub(super) mask: Bitboard,
    pub(super) multiplier: u64,
    shift: u32,
    offset: u32, // Entries, not bytes, from the beginning of ATTACKS.
}

impl Magic {
    pub(super) const fn index(self, occupied: Bitboard) -> usize {
        let hash = (occupied.bits() & self.mask.bits()).wrapping_mul(self.multiplier) >> self.shift;
        self.offset as usize + hash as usize
    }
}

// Rooks a1..h8 followed by bishops a1..h8. Only these 128 small descriptors
// use const evaluation; the large attack table is generated by build.rs.
pub(super) static MAGICS: [Magic; 128] = build_metadata();

const fn build_metadata() -> [Magic; 128] {
    let mut magics = [Magic {
        mask: Bitboard::EMPTY,
        multiplier: 0,
        shift: 0,
        offset: 0,
    }; 128];
    let mut entry = 0;
    let mut offset = 0;
    while entry < magics.len() {
        let index = entry % 64;
        let square = Square::new(index as u8).unwrap();
        let (mask, multiplier) = if entry < 64 {
            (rook_mask(square), ROOK_MULTIPLIERS[index])
        } else {
            (bishop_mask(square), BISHOP_MULTIPLIERS[index])
        };
        magics[entry] = Magic {
            mask,
            multiplier,
            shift: 64 - mask.count(),
            offset,
        };
        offset += 1 << mask.count();
        entry += 1;
    }
    assert!(offset as usize == TABLE_LEN, "incorrect magic table size");
    magics
}

/// Occupancy bits that can change a rook's attack bitboard from `square`.
/// The rook's own rank/file may be on the board edge; only ray endpoints are
/// omitted, not the entire perimeter.
pub const fn rook_mask(square: Square) -> Bitboard {
    let file = square.file();
    let rank = square.rank();
    let mut bits = 0;
    let mut coordinate = 1;
    while coordinate < 7 {
        if coordinate != file {
            bits |= 1u64 << (rank * 8 + coordinate);
        }
        if coordinate != rank {
            bits |= 1u64 << (coordinate * 8 + file);
        }
        coordinate += 1;
    }
    Bitboard::from_bits(bits)
}

/// Occupancy bits that can change a bishop's attack bitboard from `square`.
/// Diagonal ray endpoints are always on the perimeter, so all candidate
/// blocker squares here have both file and rank in 1..7.
pub const fn bishop_mask(square: Square) -> Bitboard {
    let mut bits = 0;
    let mut rank = 1;
    while rank < 7 {
        let mut file = 1;
        while file < 7 {
            let df = file as i8 - square.file() as i8;
            let dr = rank as i8 - square.rank() as i8;
            if df != 0 && (df == dr || df == -dr) {
                bits |= 1u64 << (rank * 8 + file);
            }
            file += 1;
        }
        rank += 1;
    }
    Bitboard::from_bits(bits)
}
