//! Magic bitboard lookups into the table generated by build.rs.
//!
//! A relevant occupancy mask excludes the origin and the final square on each
//! ray: occupying a terminal square cannot change the attack bitboard, since
//! attacks include the first blocker. Masks retain every other square on the
//! rays, even squares that a nearer blocker might hide in a particular position.
//! The `magic_search` development example searches and verifies multipliers.
//! Runtime calls only mask, multiply, shift, and index prebuilt static data.

#[cfg(test)]
mod generate;
mod layout;

#[cfg(test)]
use super::reference;
use crate::{Bitboard, Square};
use layout::{MAGICS, TABLE_LEN};

pub use layout::{bishop_mask, rook_mask};

// The native build script materializes this contiguous array as Rust literals.
// Runtime lookups need neither initialization nor access to the generated file.
include!(concat!(env!("OUT_DIR"), "/magic_attacks.rs"));

/// Rook attack geometry, including the first blocker of either color on each ray.
#[inline]
pub fn rook_attacks(square: Square, occupied: Bitboard) -> Bitboard {
    ATTACKS[MAGICS[square.index()].index(occupied)]
}

/// Bishop attack geometry, including the first blocker of either color on each ray.
#[inline]
pub fn bishop_attacks(square: Square, occupied: Bitboard) -> Bitboard {
    ATTACKS[MAGICS[64 + square.index()].index(occupied)]
}

/// Combines the rook and bishop lookup results; it does not check move legality.
#[inline]
pub fn queen_attacks(square: Square, occupied: Bitboard) -> Bitboard {
    rook_attacks(square, occupied) | bishop_attacks(square, occupied)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::attacks::reference;

    #[test]
    fn corner_and_center_masks_have_expected_bits() {
        const A1: Square = Square::new(0).unwrap();
        const D4: Square = Square::from_coords(3, 3).unwrap();
        const ROOK_A1: Bitboard = rook_mask(A1);
        const BISHOP_A1: Bitboard = bishop_mask(A1);
        assert_eq!(ROOK_A1.bits(), 0x0001_0101_0101_017e);
        assert_eq!(BISHOP_A1.bits(), 0x0040_2010_0804_0200);
        assert_eq!(ROOK_A1.count(), 12);
        assert_eq!(BISHOP_A1.count(), 6);
        assert_eq!(rook_mask(D4).count(), 10);
        assert_eq!(bishop_mask(D4).count(), 9);
    }

    #[test]
    fn masks_contain_exactly_the_single_blockers_that_change_attacks() {
        for index in 0..64 {
            let from = Square::new(index).unwrap();
            let empty_rook = reference::rook_attacks(from, Bitboard::EMPTY);
            let empty_bishop = reference::bishop_attacks(from, Bitboard::EMPTY);
            for blocker in 0..64 {
                let blocker = Square::new(blocker).unwrap();
                let occupied = Bitboard::from_square(blocker);
                assert_eq!(
                    rook_mask(from).contains(blocker),
                    reference::rook_attacks(from, occupied) != empty_rook,
                    "rook {from}, blocker {blocker}"
                );
                assert_eq!(
                    bishop_mask(from).contains(blocker),
                    reference::bishop_attacks(from, occupied) != empty_bishop,
                    "bishop {from}, blocker {blocker}"
                );
            }
        }
    }

    #[test]
    fn every_relevant_subset_is_unique_and_ignored_occupancy_cannot_change_attacks() {
        type AttackFn = fn(Square, Bitboard) -> Bitboard;
        let mut total = 0;
        for index in 0..64 {
            let from = Square::new(index).unwrap();
            let cases: [(Bitboard, AttackFn); 2] = [
                (rook_mask(from), reference::rook_attacks),
                (bishop_mask(from), reference::bishop_attacks),
            ];
            for (mask, attacks) in cases {
                assert!(!mask.contains(from));
                assert!(mask.count() <= 12);
                let mut previous = None;
                let mut count = 0;
                for subset in mask.subsets() {
                    assert!((subset & !mask).is_empty());
                    if let Some(previous) = previous {
                        assert!(subset.bits() > previous);
                    } else {
                        assert!(subset.is_empty());
                    }
                    // Fill every excluded square at once: origin, ray endpoints,
                    // and all off-ray squares. The same attack result must hold.
                    assert_eq!(
                        attacks(from, subset),
                        attacks(from, subset | !mask),
                        "{from}, mask {mask:?}, subset {subset:?}"
                    );
                    previous = Some(subset.bits());
                    count += 1;
                }
                assert_eq!(previous, Some(mask.bits()));
                assert_eq!(count, 1 << mask.count());
                total += count;
            }
        }
        assert_eq!(total, 107_648);
    }
}
