use std::{
    env,
    fs::File,
    io::{self, BufWriter, Write},
    path::PathBuf,
};

// Compile the same small source modules for the host build script. This avoids
// a dependency on the library being built, or a second implementation of geometry.
#[path = "src/types/bitboard.rs"]
mod bitboard;
#[path = "src/formatting.rs"]
mod formatting;
#[path = "src/types/square.rs"]
mod square;
pub use bitboard::Bitboard;
pub use square::Square;

#[path = "src/attacks/magic/generate.rs"]
mod generate;
#[path = "src/attacks/magic/layout.rs"]
mod layout;
#[path = "src/attacks/reference.rs"]
pub mod reference;

fn main() -> io::Result<()> {
    for source in [
        "build.rs",
        "src/types/bitboard.rs",
        "src/types/square.rs",
        "src/formatting.rs",
        "src/attacks/reference.rs",
        "src/attacks/magic/generate.rs",
        "src/attacks/magic/layout.rs",
        "src/attacks/magic/multipliers.rs",
    ] {
        println!("cargo::rerun-if-changed={source}");
    }

    let table = generate::build_attacks(&layout::MAGICS);
    let output = PathBuf::from(env::var_os("OUT_DIR").expect("Cargo supplies OUT_DIR"));
    let mut source = BufWriter::new(File::create(output.join("magic_attacks.rs"))?);
    writeln!(
        source,
        "// Generated by build.rs from verified magic multipliers."
    )?;
    writeln!(source, "static ATTACKS: [Bitboard; TABLE_LEN] = [")?;
    for attacks in table {
        writeln!(source, "    Bitboard::from_bits({:#018x}),", attacks.bits())?;
    }
    writeln!(source, "];")?;
    source.flush()
}
